version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_tests
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodb
            MONGO_INITDB_ROOT_PASSWORD: docker
            MONGO_INITDB_DATABASE: tests
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro